version: '3.8'

services:
  server:
    image: ranpick-backend
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - SECRET=${SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - DATABASE_URL=${DATABASE_URL}
  client:
    image: ranpick-frontend
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server