name: Build Client and Commit

on:
  push:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Commit and push client build
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add server/dist
          git commit -m "Build client [skip ci]" || echo "No changes to commit"
          git push