name: Build and Deploy Project

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Server dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        run: |
          cd server
          npm install

      - name: Install Client dependencies
        run: |
          cd client
          npm install

      - name: Setup Prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        run: |
          cd server
          npx prisma generate
          npx prisma migrate deploy

      - name: Build client
        run: |
          cd client
          npm run build:dev

      - name: Run Server
        env:
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        run: |
          cd server
          npm run start:test &

      - name: Wait for the server to be ready
        run: |
          npm install -g wait-on
          npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: |
          cd tests
          npm install
          npx playwright install-deps
          npx playwright install
          npm run test